[project]
name = "quotes-bot"
version = "v3.3.15"
description = " Python Discord bot for archiving quotes in a database and some extra utility"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "disnake>=2.12.1",
    "environs>=15.0.1",
    "mcstatus>=14.0.0",
    "pytz>=2026.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]
